---
##############################
# This playbook in called by Vagrant for initial VM provisioning.
# It installs the basic kubernetes cluster

- hosts: all
  gather_facts: false
  become: true
  any_errors_fatal: true
  tasks:
    - name: Install python
      raw: yum install -y python libselinux-python

- hosts: all
  become: true
  any_errors_fatal: true
  roles:
    - common

- hosts: master
  become: true
  any_errors_fatal: true
  roles:
    - k8s-master

- hosts: workers
  become: true
  any_errors_fatal: true
  roles:
    - k8s-worker

- hosts: master
  become: false
  any_errors_fatal: true
  tasks:
    - name: Retrieve kube config
      fetch:
        src: /home/vagrant/.kube/config
        dest: ../kubeconfig
        flat: true

    - name: Wait for workers to be ready
      shell: test "$(kubectl get nodes {{ item }} --no-headers |
             awk '{ print $2 }')" = "Ready"
      register: task_result
      until: task_result.rc == 0
      delay: 10
      retries: 60
      changed_when: false
      with_items: "{{ groups['workers'] }}"

    - name: Label workers with worker role
      command: "kubectl label --overwrite no/{{ item }} node-role.kubernetes.io/worker=''"
      with_items: "{{ groups['workers'] }}"

- hosts: localhost
  gather_facts: false
  become: false
  any_errors_fatal: true
  vars:
    - kubeconfig: ../kubeconfig
  tasks:
    - name: Look for helm
      command: "which helm"
      register: which_helm
      changed_when: false
      failed_when: which_helm.rc != 0 and which_helm.rc != 1

    - block:
        - set_fact:
            helm: "{{ which_helm.stdout }}"

        - name: Create service account for Tiller
          command: >-
                  kubectl
                  --kubeconfig=../kubeconfig
                  apply -f files/helm-tiller-sa.yml

        - name: Install Tiller
          command: >-
                  {{ helm }} init
                  --kubeconfig=../kubeconfig
                  --service-account tiller
      when: which_helm.rc == 0

